### ISSUE TITLE
Account icon (NavBar button)

### ISSUE THREAD

**Issue by HoveringTorso** [marcuskrueger90/GetLost#7]
Maybe the 'account' or 'profile' button in the NavBar is an icon and dropdown options that all change based on logged in/out status.
- 	If the user is logged out:
 	- 	'Sign Up' dropdown option that links to 'Sign Up' page **[MVP]**
 	- 	'Log In' dropdown option that links to 'Log In' page **[MVP]**
- 	If the user is logged in:
 	- 	Account icon in the navbar could be replaced by the current user's name _[Stretch Goal]_
 	- 	'Account Info' dropdown option that links to 'Account Info' page _[Stretch Goal]_
 	- 	'Log Out' dropdown option that links to a /logout route (which is probably an Express route that eventually sends the 'guest' user back to the home page) **[MVP]**

**Comment by Ieapplekamp** [comment]
I think all of this was taken care of with the authentication, might very a little bit in the overall end. Login, Register, and then there is a log out button on the Dashboard page. On the Dashboard a username pops up as well, but I believe that's being moved to the nav
